---
all:
  vars:
    # host_key_checking: false
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: devops
  children:
    http:
      children:
        web:
          hosts:
            web-1-do-nyc3-us.forwardemail.net:
              ansible_host: 0.0.0.0
        api:
          hosts:
            api-1-do-nyc3-us.api.forwardemail.net:
              ansible_host: 0.0.0.0
    bree:
      hosts:
        bree-1-do-nyc3-us.forwardemail.net:
          ansible_host: 0.0.0.0
