---
- name: Import security playbook
  ansible.builtin.import_playbook: security.yml
- name: Import Node.js playbook
  ansible.builtin.import_playbook: node.yml
- name: Import SSH keys playbook
  ansible.builtin.import_playbook: ssh-keys.yml
- hosts: bree
  name: Bree
  become: true
  become_user: root
  roles:
    # https://github.com/holms/ansible-fqdn
    - role: fqdn
  tasks:
    # ufw
    - name: Enable ufw
      ufw:
        state: enabled
        policy: deny
        direction: incoming
    - name: Limit ufw ssh
      ufw:
        rule: limit
        port: 22
        proto: tcp
    - name: Allow ssh
      ufw:
        rule: allow
        port: 22
        proto: tcp
    - name: Reload ufw
      ufw:
        state: reloaded
