---
- hosts: localhost
  name: Ecosystem
  tasks:
    #
    # https://stackoverflow.com/a/24959173
    #
    - name: Create ecosystem-web.json
      template:
        src: "{{ playbook_dir }}/templates/ecosystem-web.json.j2"
        dest: "{{ lookup('env', 'PWD') }}/ecosystem-web.json"
      delegate_to: localhost
    - name: Create ecosystem-api.json
      template:
        src: "{{ playbook_dir }}/templates/ecosystem-api.json.j2"
        dest: "{{ lookup('env', 'PWD') }}/ecosystem-api.json"
      delegate_to: localhost
    - name: Create ecosystem-bree.json
      template:
        src: "{{ playbook_dir }}/templates/ecosystem-bree.json.j2"
        dest: "{{ lookup('env', 'PWD') }}/ecosystem-bree.json"
      delegate_to: localhost
