---
- name: Import security playbook
  ansible.builtin.import_playbook: security.yml
- name: Import Node.js playbook
  ansible.builtin.import_playbook: node.yml
- name: Import SSH keys playbook
  ansible.builtin.import_playbook: ssh-keys.yml
- hosts: web
  name: HTTP
  become: true
  become_user: root
  tasks:
    - name: Set hostname
      hostname:
        name: "{{ lookup('env', 'WEB_HOST') }}"
  roles:
    # https://github.com/holms/ansible-fqdn
    - role: fqdn
      fqdn: "{{ lookup('env', 'WEB_HOST') }}"
- hosts: api
  name: HTTP
  become: true
  become_user: root
  tasks:
    - name: Set hostname
      hostname:
        name: "{{ lookup('env', 'API_HOST') }}"
  roles:
    # https://github.com/holms/ansible-fqdn
    - role: fqdn
      fqdn: "{{ lookup('env', 'API_HOST') }}"
- hosts: web:api
  name: HTTP
  become: true
  become_user: root
  # this was already defined in the ufw role
  # https://github.com/Oefenweb/ansible-ufw/blob/master/handlers/main.yml
  handlers:
    - name: Reload UFW
      ufw:
        state: reloaded
  tasks:
    # ufw
    - name: Enable ufw
      ufw:
        state: enabled
        policy: deny
        direction: incoming
    - name: Limit ufw ssh
      ufw:
        rule: limit
        port: 22
        proto: tcp
    - name: Set UFW default forward policy to ACCEPT
      lineinfile:
        dest: /etc/default/ufw
        line: DEFAULT_FORWARD_POLICY="ACCEPT"
        regexp: ^DEFAULT_FORWARD_POLICY\=
    - name: Allow ssh
      ufw:
        rule: allow
        port: 22
        proto: tcp
    - name: Allow http
      ufw:
        rule: allow
        port: 80
        proto: tcp
    - name: Allow https
      ufw:
        rule: allow
        port: 443
        proto: tcp
    - name: Allow http forwarder
      ufw:
        rule: allow
        port: "{{ lookup('env', 'PROXY_PORT') }}"
        proto: tcp
    - name: Allow https forwarder
      ufw:
        rule: allow
        port: "{{ lookup('env', 'HTTP_PORT') }}"
        proto: tcp
    #
    # modify ufw setup
    # https://github.com/Oefenweb/ansible-ufw/issues/21
    #
    - name: "Update ufw before.rules until #21 is resolved"
      template:
        src: "{{ playbook_dir }}/templates/before.rules.j2"
        dest: /etc/ufw/before.rules
        owner: root
        group: root
        mode: "0644"
      notify: Reload UFW
