---
- hosts: http:bree
  name: Node.js
  become: true
  become_user: root
  tasks:
    # install n and node lts
    - name: Check that n exists
      stat:
        path: /home/deploy/n
      register: n_result
    - name: Install n
      become: true
      become_user: deploy
      shell:
        cmd: curl -L https://raw.githubusercontent.com/mklement0/n-install/stable/bin/n-install | bash -s -- -y
      when: not n_result.stat.exists
    # install pm2 and pnpm
    - name: Check if pm2 exists
      stat:
        path: /home/deploy/n/bin/pm2
      register: pm2_result
    - name: Install pm2
      become: true
      become_user: deploy
      shell: bash -ilc 'npm install -g pm2'
      when: not pm2_result.stat.exists
    - name: Check if pnpm exists
      stat:
        path: /home/deploy/n/bin/pnpm
      register: pnpm_result
    - name: Install pnpm
      become: true
      become_user: deploy
      shell: bash -ilc 'npm install -g pnpm@7'
      when: not pnpm_result.stat.exists
    # install fonts
    - name: Accept fonts license
      shell:
        cmd: echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections
    - name: Install fonts
      apt:
        name:
          - xfonts-75dpi
          - fontconfig
          - libxrender1
          - xfonts-base
          - ttf-mscorefonts-installer
          - libfontconfig
        update_cache: true
    # install wkhtmltopdf
    - name: Install wkhtmltopdf
      shell: |
        wget "https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6.1-2/wkhtmltox_0.12.6.1-2.$(lsb_release -c -s)_$(dpkg --print-architecture).deb"
        sudo dpkg -i "wkhtmltox_0.12.6.1-2.$(lsb_release -c -s)_$(dpkg --print-architecture).deb"
    # configure pm2
    - name: Create pm2 directory
      file:
        path: /var/www
        state: directory
        owner: www-data
        group: www-data
        # https://chmodcommand.com/chmod-770/
        mode: "0770"
        recurse: true
    - name: Install pm2-logrotate
      become: true
      become_user: deploy
      shell: bash -ilc 'pm2 install pm2-logrotate'
    - name: Check that pm2 startup script exists
      stat:
        path: /etc/systemd/system/pm2-deploy.service
      register: pm2_startup_result
    - name: Install pm2 startup script
      shell: sudo env PATH=$PATH:/home/deploy/n/bin pm2 startup ubuntu -u deploy --hp /home/deploy
